---
abstract: "Apocalypse's favorite tests bundled into a simple interface"
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Apocalypse
provides:
  Test::Apocalypse:
    file: lib/Test/Apocalypse.pm
    version: 0.09
  Test::Apocalypse::AutoLoader:
    file: lib/Test/Apocalypse/AutoLoader.pm
    version: 0.09
  Test::Apocalypse::CPANMeta:
    file: lib/Test/Apocalypse/CPANMeta.pm
    version: 0.09
  Test::Apocalypse::CheckChanges:
    file: lib/Test/Apocalypse/CheckChanges.pm
    version: 0.09
  Test::Apocalypse::Compile:
    file: lib/Test/Apocalypse/Compile.pm
    version: 0.09
  Test::Apocalypse::ConsistentVersion:
    file: lib/Test/Apocalypse/ConsistentVersion.pm
    version: 0.09
  Test::Apocalypse::DOSnewline:
    file: lib/Test/Apocalypse/DOSnewline.pm
    version: 0.09
  Test::Apocalypse::Dependencies:
    file: lib/Test/Apocalypse/Dependencies.pm
    version: 0.09
  Test::Apocalypse::DirChecks:
    file: lib/Test/Apocalypse/DirChecks.pm
    version: 0.09
  Test::Apocalypse::DistManifest:
    file: lib/Test/Apocalypse/DistManifest.pm
    version: 0.09
  Test::Apocalypse::Distribution:
    file: lib/Test/Apocalypse/Distribution.pm
    version: 0.09
  Test::Apocalypse::EOL:
    file: lib/Test/Apocalypse/EOL.pm
    version: 0.09
  Test::Apocalypse::FileChecks:
    file: lib/Test/Apocalypse/FileChecks.pm
    version: 0.09
  Test::Apocalypse::FilePortability:
    file: lib/Test/Apocalypse/FilePortability.pm
    version: 0.09
  Test::Apocalypse::Fixme:
    file: lib/Test/Apocalypse/Fixme.pm
    version: 0.09
  Test::Apocalypse::HasVersion:
    file: lib/Test/Apocalypse/HasVersion.pm
    version: 0.09
  Test::Apocalypse::JSONMeta:
    file: lib/Test/Apocalypse/JSONMeta.pm
    version: 0.09
  Test::Apocalypse::Kwalitee:
    file: lib/Test/Apocalypse/Kwalitee.pm
    version: 0.09
  Test::Apocalypse::METAyml:
    file: lib/Test/Apocalypse/METAyml.pm
    version: 0.09
  Test::Apocalypse::MinimumVersion:
    file: lib/Test/Apocalypse/MinimumVersion.pm
    version: 0.09
  Test::Apocalypse::ModuleUsed:
    file: lib/Test/Apocalypse/ModuleUsed.pm
    version: 0.09
  Test::Apocalypse::NoBreakpoints:
    file: lib/Test/Apocalypse/NoBreakpoints.pm
    version: 0.09
  Test::Apocalypse::OutdatedPrereqs:
    file: lib/Test/Apocalypse/OutdatedPrereqs.pm
    version: 0.09
  Test::Apocalypse::PPPort:
    file: lib/Test/Apocalypse/PPPort.pm
    version: 0.09
  Test::Apocalypse::PerlCritic:
    file: lib/Test/Apocalypse/PerlCritic.pm
    version: 0.09
  Test::Apocalypse::PerlMetrics:
    file: lib/Test/Apocalypse/PerlMetrics.pm
    version: 0.09
  Test::Apocalypse::Pod:
    file: lib/Test/Apocalypse/Pod.pm
    version: 0.09
  Test::Apocalypse::Pod_Coverage:
    file: lib/Test/Apocalypse/Pod_Coverage.pm
    version: 0.09
  Test::Apocalypse::Pod_No404s:
    file: lib/Test/Apocalypse/Pod_No404s.pm
    version: 0.09
  Test::Apocalypse::Pod_Spelling:
    file: lib/Test/Apocalypse/Pod_Spelling.pm
    version: 0.09
  Test::Apocalypse::Prereq:
    file: lib/Test/Apocalypse/Prereq.pm
    version: 0.09
  Test::Apocalypse::Prereq_Build:
    file: lib/Test/Apocalypse/Prereq_Build.pm
    version: 0.09
  Test::Apocalypse::Signature:
    file: lib/Test/Apocalypse/Signature.pm
    version: 0.09
  Test::Apocalypse::Strict:
    file: lib/Test/Apocalypse/Strict.pm
    version: 0.09
  Test::Apocalypse::Synopsis:
    file: lib/Test/Apocalypse/Synopsis.pm
    version: 0.09
  Test::Apocalypse::UseAllModules:
    file: lib/Test/Apocalypse/UseAllModules.pm
    version: 0.09
requires:
  CPANPLUS: 0.90
  Devel::PPPort: 3.19
  File::Find::Rule: 0.32
  File::Spec: 3.31
  File::Which: 1.09
  Module::CPANTS::Analyse: 0.85
  Module::CoreList: 2.23
  Module::Pluggable: 3.9
  Perl::Metrics::Simple: 0.13
  Task::Perl::Critic: 1.007
  Test::AutoLoader: 0.03
  Test::Block: 0.11
  Test::CPAN::Meta: 0.13
  Test::CheckChanges: 0.08
  Test::Compile: 0.11
  Test::ConsistentVersion: 0.002002
  Test::Dependencies: 0.12
  Test::Dir: 1.006
  Test::DistManifest: 1.005
  Test::Distribution: 2.00
  Test::EOL: 0.3
  Test::File: 1.29
  Test::Fixme: 0.04
  Test::HasVersion: 0.012
  Test::JSON::Meta: 0.04
  Test::MinimumVersion: 0.011
  Test::Module::Used: 0.001002
  Test::More: 0.94
  Test::NoBreakpoints: 0.13
  Test::NoWarnings: 0.084
  Test::Perl::Critic: 1.02
  Test::Pod: 1.40
  Test::Pod::Coverage: 1.08
  Test::Pod::No404s: 0.01
  Test::Portability::Files: 0.05
  Test::Prereq: 1.037
  Test::Prereq::Build: 1.037
  Test::Signature: 1.10
  Test::Spelling: 0.11
  Test::Strict: 0.13
  Test::Synopsis: 0.06
  Test::UseAllModules: 0.12
  Test::YAML::Meta: 0.14
  YAML: 0.70
  perl: 5.008
  version: 0.77
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Apocalypse
  homepage: http://search.cpan.org/dist/Test-Apocalypse
  license: http://dev.perl.org/licenses/
  repository: http://github.com/apocalypse/perl-test-apocalypse
version: 0.09
